### ISSUE TITLE
Suggestion for Quiz 2: Nightscout

### ISSUE THREAD

**Issue by dybs** [LoopKit/loopdocs#170]
The wording on the question about the Loop pill's ⚠ symbol is a bit subtle.  I interpreted it as meaning that the symbol indicates a red Loop (so I selected false, since it just indicates Nightscout isn't getting Loop data).  I think it might be clearer to make this a multiple choice question such as:

What does a ⚠ symbol indicate in the Loop pill?
* Loop is red
* Nightscout has not received Loop data for more than 5 minutes.  Loop status is otherwise unknown.
* Nightscout has not received Loop data for more than 5 minutes, and Loop is red

**Comment by Kdisimone** [comment]
It's intentionally written in a way that might be hard to answer because I want people to realize it's not just possible to be one certain answer all the time. It can be that Loop is still green, just not uploading to NS. And Loop could have received upload in last 5 min but is red. So your answers aren't quite right as written. It's an oft mis-understood symbol.

**Comment by dybs** [comment]
Ah, right, I just looked back at the docs on saw it could mean a red Loop as well.  My bad.

Where would I find more details about the difference between this symbol and the "X Error in Loop" symbol?  Does that indicate a red Loop as well, or some other problem?  I searched both Loopdocs and Looptips but didn't see any other info about them?
