### ISSUE TITLE
Homebrew/carthage 

### ISSUE THREAD

**Issue by ps2** [LoopKit/loopdocs#21]
Homebrew/carthage installation section can be removed, or moved somewhere else as a reference, since the build phase auto-sets those up now.

**Comment by Kdisimone** [comment]
I'm almost did this today...but on a new install with first time users (Xcode 9.3 fresh installation), the build fails before homebrew and carthage can get added.  So in order to run carthage bootstrap, homebrew had to be added manually.  I'll come back to this part of docs soon and move it to a reference section somewhere that makes sense.

**Comment by Kdisimone** [comment]
@ps2 does homebrew really auto install?  I ran a test case on a computer that didn't have it installed and the build failed for lack of homebrew.  I can try again if that was a fluke.

**Comment by Kdisimone** [comment]
But, I have taken out the carthage installation part from the directions.  I'll await confirmation about the homebrew

**Comment by marionbarker** [comment]
I believe this issue should be closed. I think Issue 205 supersedes this.
